### ISSUE TITLE
ports

### ISSUE THREAD

**Issue by vcfff** [openiomon/hds2graphite#2]
hi may you share info which ports to be  opened in order to have it functional in isolated network, thank you

**Comment by munokar** [comment]
Hi,
can you specify the port for which component you are looking (Graphite, Storage, TuningManager, Infrastructure Analytics Advisor)?

Regards

Timo

**Comment by vcfff** [comment]
![components](https://user-images.githubusercontent.com/34322438/87475663-05daf700-c5da-11ea-90e9-ce79b3ae9de8.jpg)

Hi, attached sketched components and those marked in squares, not sure which ones are for me mandatory, if just port exposed for Grafana web dashboard site. One more thing it will work as well with new VSP 5k Series + taking data from HDS Ops Centre?

Thank you

**Comment by munokar** [comment]
Hi,
that looks like basically all communication.

Let's start in another way: Do you have a running Grafana infrastructure with a graphite / carbon backend? OpenIOmon modules are only containing software to retrieve data from Hitachi storage or Broadcom switches. All the other components are open source software not part of OpenIOmon (hds2graphite).

Grafana: https://grafana.com/
Carbon (I would recommend go-carbon): https://github.com/go-graphite/go-carbon
Graphite (I would recommend graphite-api which is part of CentOS / RHEL EPEL): https://centos.pkgs.org/7/epel-x86_64/graphite-api-1.1.3-3.el7.noarch.rpm.html

Most of the network ports you are asking for are subject of the configuration of these elements (e.g. Default Grafana Port is 3000 but in most cases changed during configuration to 443 or 80). The port used from HDS2GRAPHITE to send data to go-carbon is normally 2003 but this can also be changed in the configuration. 
To simplify the setup you can install Grafana, Carbon, Graphite-API and HDS2GRAPHITE on one single system. Then you only need to open the port in the firewall used to access Grafana (default would be 3000) and the port to communicate with OpsCenter Analyzer and the storage via Export Tool.

Regarding firewall ports needed for export tool the G5000 Perfomance Optimzation Guide states:

> If a firewall exists between the Device Manager - Storage Navigator
> computer and the SVP, see the System Administrator Guide. In the section
> “Setting up TCP/IP for a firewallȋ, the RMI port numbers listed are the only
> direct communication settings required for Export Tool.

So you need to look into the System Administrator Guide for the port details. Currently I don't have the infos available.

Your question regarding G5000:
I have not tested it with a G5000 since I don't have one ;-) In general ExportTool is available and it looks the same as for the G1500. Since OpsCenter Analyzer is nothing else then Hitachi Infrastructure Analytics Advisor (HIAA) this should also work.

Perhaps there will be a chance for me in the next 3 - 4 weeks to test this a lab where G5000 is available...

Regards
Timo

**Comment by vcfff** [comment]
hi, i am in preparation phase to try it out in our isolated network, so asking in advance what its needed and not. thank you
